# Number of generated items
amounts:
  flavors: 50
  service_instances: 50     # belongs_to [:source_region, :service_offering, :service_plan]
  service_offerings: 100    # belongs_to [:source_region]
  service_plans: 150        # belongs_to [:source_region, :service_offering]
  source_regions: 50
  volumes: 100              # belongs_to [:volume_type, :source_region]
  volume_types: 50
  vms: 100                  # belongs_to [:flavor]

