# Number of generated items
amounts:
  container_images: 5
  container_groups: 10
  container_projects: 2
  container_nodes: 5
  container_templates: 5
  service_instances: 10
  service_offerings: 2
  service_offering_icons: 2
  service_plans: 5

default_limit: 100 # Number of entities to send at once to ingress api

events:
  check_interval: 1 #second
  checks_count: 1
  per_check:
    add: 1
    modify: 1
    delete: 0

full_refresh:
  # Total round of generating
  repeats_count: 1
  # Order of generating InventoryCollections:
  # - :normal - top level first, dependent later
  # - :reversed - dependent first
  send_order: :normal

# Generate and send entities in parallel
# - :on
# - :off
multithreading: :off

# Strategy for generating Unique IDs
# - :human_readable - sequential, human readable format
# - :uuids          - sequential in UUID format
uuid_strategy: :uuids
